apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  name: "bitnami-helm-repository"
stringData:
  name: "bitnami"
  type: "helm"
  url: "registry-1.docker.io/bitnamicharts"
  enableOCI: "true"