apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  name: "istio-helm-repository"
stringData:
  name: "knative"
  type: "helm"
  url: "https://istio-release.storage.googleapis.com/charts"