apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  name: "knative-helm-repository"
stringData:
  name: "knative"
  type: "helm"
  url: "https://knative.github.io/operator"