apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: "root-git-repository"
  namespace: argocd
stringData:
  name: "root"
  type: "git"
  url: "${REPO_URL}"