apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: debezium
spec:
  rules:
    - name: debezium
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - debezium
      mutate:
        patchStrategicMerge:
          spec:
            nodeSelector:
              tier: medium
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: debezium
  namespace: argocd
spec:
  destination:
    namespace: "debezium"
    server: https://kubernetes.default.svc
  source:
    path: "infra/debezium"
    repoURL: "${REPO_URL}"
    helm:
      valuesObject:
        properties: |
          debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
          debezium.source.offset.flush.interval.ms=0
          debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
          debezium.source.schema.history.internal.file.filename=/debezium/data/schema-history.dat
          debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector
          debezium.source.database.hostname=${DB_HOST}
          debezium.source.database.port=${DB_PORT}
          debezium.source.database.user=${DB_USER}
          debezium.source.database.password=${DB_PASSWORD}
          debezium.source.database.server.id=1
          debezium.source.topic.prefix=mysql
          debezium.sink.type=rabbitmq
          debezium.sink.rabbitmq.connection.host=${AMQP_HOST}
          debezium.sink.rabbitmq.connection.port=${AMQP_PORT}
          debezium.sink.rabbitmq.connection.username=${AMQP_USER}
          debezium.sink.rabbitmq.connection.password=${AMQP_PASSWORD}
          debezium.sink.rabbitmq.connection.virtual.host=${AMQP_VHOST}
          debezium.sink.rabbitmq.ackTimeout=3000
          debezium.sink.rabbitmq.exchange=cdc
          debezium.sink.rabbitmq.routingKeyFromTopicName=true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Wait=true
