apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: "1.25.0"
      helm:
        valuesObject:
          defaultRevision: default
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: "1.25.0"
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: "1.25.0"
  destination:
    namespace: "istio-system"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Wait=true