apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: phpmyadmin
spec:
  rules:
    - name: phpmyadmin
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - phpmyadmin
      mutate:
        patchStrategicMerge:
          spec:
            nodeSelector:
              tier: low
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phpmyadmin
  namespace: argocd
spec:
  destination:
    namespace: phpmyadmin
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: registry-1.docker.io/bitnamicharts
    chart: phpmyadmin
    targetRevision: "18.1.4"
    helm:
      valuesObject:
        db:
          allowArbitraryServer: false
          host: "${DB_HOST}"
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Wait=true
