apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: testing
  namespace: "{{.Release.Namespace}}"
spec:
  name: testing
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: "{{.Release.Namespace}}"